// Package ocserv drives a local ocserv install: rendering its config, issuing
// certs, supervising the process, and reading live state over occtl. This file
// renders ocserv.conf from a high-level InstanceConfig.
package ocserv

import (
	"fmt"
	"net"
	"sort"
	"strings"

	"github.com/reloadlife/openconnectd/pkg/api"
)

// InstanceConfig is everything needed to render one ocserv.conf. It is derived
// from api.Instance plus resolved on-disk paths (certs, sockets, run dir).
type InstanceConfig struct {
	Name string

	TCPPort   int
	UDPPort   int // 0 disables DTLS
	LocalBind string

	PoolCIDR   string // "10.10.10.0/24"
	PoolCIDRv6 string
	DNS        []string
	Routes     []string // empty ⇒ full tunnel (no explicit route lines)

	AuthMode   api.AuthMode
	Camouflage api.Camouflage

	// Resolved paths (owned by the daemon, not the caller).
	ServerCert   string // fullchain PEM
	ServerKey    string
	CACert       string // client-CA for cert auth (empty for password-only)
	CRLFile      string // revocation list for cert auth (optional)
	OcpasswdFile string // for plain auth
	OcctlSocket  string
	RunSocket    string
	Device       string // tun device basename, e.g. "oc-<name>"
	// ConfigPerUserDir holds one file per common name, each pinning that
	// client's address with explicit-ipv4. Empty ⇒ directive omitted, and
	// ocserv assigns pool addresses in connect order.
	ConfigPerUserDir string

	MaxClients     int
	MaxSameClients int
	DefaultDomain  string
}

// Render produces a complete ocserv.conf. It is pure (no I/O) so it is unit
// testable; the process layer writes the result and reloads ocserv.
func (c InstanceConfig) Render() (string, error) {
	if err := c.validate(); err != nil {
		return "", err
	}
	var b strings.Builder
	p := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }

	p("# Generated by openconnectd for instance %q. Do not edit by hand.", c.Name)
	p("")

	// --- auth ---
	// cert-primary is expressed as auth=certificate; password/both add a plain
	// auth backend. ocserv evaluates enable-auth stacking for "both".
	switch c.AuthMode {
	case api.AuthPassword:
		p("auth = \"plain[passwd=%s]\"", c.OcpasswdFile)
	case api.AuthBoth:
		p("auth = \"certificate\"")
		p("enable-auth = \"plain[passwd=%s]\"", c.OcpasswdFile)
	default: // AuthCert (and unset)
		p("auth = \"certificate\"")
	}
	if c.AuthMode == api.AuthCert || c.AuthMode == api.AuthBoth {
		if c.CACert == "" {
			return "", fmt.Errorf("ocserv: cert auth needs a client CA")
		}
		p("ca-cert = %s", c.CACert)
		// Map the client cert CN to the ocserv username (OID 2.5.4.3 = CN).
		p("cert-user-oid = 2.5.4.3")
		if c.CRLFile != "" {
			p("crl = %s", c.CRLFile)
		}
	}
	p("")

	// --- listeners ---
	p("server-cert = %s", c.ServerCert)
	p("server-key = %s", c.ServerKey)
	p("tcp-port = %d", c.TCPPort)
	if c.UDPPort > 0 {
		p("udp-port = %d", c.UDPPort) // DTLS fast path
	}
	if c.LocalBind != "" {
		p("listen-host = %s", c.LocalBind)
	}
	// socket-file is the sec-mod base (ocserv suffixes it per worker).
	// occtl-socket-file is the per-instance occtl control socket occtl connects
	// to; without a distinct path every instance shares /var/run/occtl.socket.
	// use-occtl must be true or the occtl socket is never served.
	p("socket-file = %s", c.RunSocket)
	p("occtl-socket-file = %s", c.OcctlSocket)
	p("use-occtl = true")
	p("device = %s", c.Device)
	// Per-user overrides. Without this directive ocserv never reads the files,
	// so a client's pinned address is silently ignored and every control-plane
	// rule keyed on that address matches nothing.
	if c.ConfigPerUserDir != "" {
		p("config-per-user = %s", c.ConfigPerUserDir)
	}
	p("")

	// --- camouflage (anti active-probing DPI) ---
	if c.Camouflage.Enabled {
		if c.Camouflage.Secret == "" {
			return "", fmt.Errorf("ocserv: camouflage enabled but secret empty")
		}
		p("camouflage = true")
		p("camouflage_secret = \"%s\"", c.Camouflage.Secret)
		if c.Camouflage.Realm != "" {
			p("camouflage_realm = \"%s\"", c.Camouflage.Realm)
		}
		p("")
	}

	// --- network ---
	ipnet, mask, err := splitCIDR(c.PoolCIDR)
	if err != nil {
		return "", err
	}
	p("ipv4-network = %s", ipnet)
	p("ipv4-netmask = %s", mask)
	if c.PoolCIDRv6 != "" {
		p("ipv6-network = %s", c.PoolCIDRv6)
	}
	for _, d := range c.DNS {
		p("dns = %s", d)
	}
	if len(c.Routes) == 0 {
		p("# full tunnel: no explicit route ⇒ default route pushed")
	} else {
		for _, r := range dedupSorted(c.Routes) {
			p("route = %s", r)
		}
	}
	if c.DefaultDomain != "" {
		p("default-domain = %s", c.DefaultDomain)
	}
	p("")

	// --- limits / hygiene ---
	p("max-clients = %d", orDefault(c.MaxClients, 1024))
	p("max-same-clients = %d", orDefault(c.MaxSameClients, 2))
	p("try-mtu-discovery = true")
	p("cisco-client-compat = true") // accept AnyConnect clients
	p("dtls-legacy = true")

	return b.String(), nil
}

func (c InstanceConfig) validate() error {
	if strings.TrimSpace(c.Name) == "" {
		return fmt.Errorf("ocserv: instance name required")
	}
	if c.TCPPort <= 0 {
		return fmt.Errorf("ocserv: tcp-port required")
	}
	if c.ServerCert == "" || c.ServerKey == "" {
		return fmt.Errorf("ocserv: server cert+key required")
	}
	if c.PoolCIDR == "" {
		return fmt.Errorf("ocserv: pool CIDR required")
	}
	return nil
}

// splitCIDR turns "10.10.10.0/24" into ("10.10.10.0", "255.255.255.0").
// ocserv wants network + dotted netmask, not CIDR notation.
func splitCIDR(cidr string) (network, netmask string, err error) {
	_, ipnet, err := net.ParseCIDR(cidr)
	if err != nil {
		return "", "", fmt.Errorf("ocserv: bad pool CIDR %q: %w", cidr, err)
	}
	m := ipnet.Mask
	if len(m) != net.IPv4len {
		return "", "", fmt.Errorf("ocserv: pool CIDR %q must be IPv4", cidr)
	}
	return ipnet.IP.String(), net.IP(m).String(), nil
}

func dedupSorted(in []string) []string {
	seen := map[string]struct{}{}
	out := make([]string, 0, len(in))
	for _, s := range in {
		if _, ok := seen[s]; ok {
			continue
		}
		seen[s] = struct{}{}
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}

func orDefault(v, def int) int {
	if v <= 0 {
		return def
	}
	return v
}

// renderPerUserConfig is the body of one config-per-user file. explicit-ipv4 is
// the only directive that overrides ocserv's pool assignment, which is what
// makes the control plane's AssignedIP the address the client actually gets.
func renderPerUserConfig(staticIP string) string {
	return "# Generated by openconnectd. Do not edit by hand.\n" +
		"explicit-ipv4 = " + staticIP + "\n"
}
